poleEmploi/config/routes.rb
Rails.application.routes.draw do
  resources :employers
  resources :reponses
  resources :demandeurs
  resources :annonces
  root 'home#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

poleEmploi/app/models/annonce.rb
class Annonce < ApplicationRecord
end

poleEmploi/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

poleEmploi/app/models/demandeur.rb
class Demandeur < ApplicationRecord
end

poleEmploi/app/models/employer.rb
class Employer < ApplicationRecord
end

poleEmploi/app/models/home.rb
class Home < ApplicationRecord
end

poleEmploi/app/models/reponse.rb
class Reponse < ApplicationRecord
end

poleEmploi/app/controllers/annonces_controller.rb
class AnnoncesController < ApplicationController
  before_action :set_annonce, only: [:show, :edit, :update, :destroy]

  # GET /annonces
  # GET /annonces.json
  def index
    @annonces = Annonce.all 
  end

  # GET /annonces/1
  # GET /annonces/1.json
  def show
  end

  # GET /annonces/new
  def new
    @annonce = Annonce.new
  end

  # GET /annonces/1/edit
  def edit
  end

  # POST /annonces
  # POST /annonces.json
  def create
    @annonce = Annonce.new(annonce_params)


      if @annonce.save
        redirect_to @annonce
      else
        render :new 
      end
    
  end

  # PATCH/PUT /annonces/1
  # PATCH/PUT /annonces/1.json
  def update

      if @annonce.update(annonce_params)
        redirect_to @annonce
      else
        render :edit
      end
  end

  # DELETE /annonces/1
  # DELETE /annonces/1.json
  def destroy
    @annonce.destroy
    redirect_to(annonces_path)
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_annonce
      @annonce = Annonce.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def annonce_params
      params.require(:annonce).permit(:title, :description, :salary, :city, :phone, :email, :skill, :qualification, :licence)
    end
end

poleEmploi/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

poleEmploi/app/controllers/demandeurs_controller.rb
class DemandeursController < ApplicationController
  before_action :set_demandeur, only: [:show, :edit, :update, :destroy]

  # GET /demandeurs
  # GET /demandeurs.json
  def index
    @demandeurs = Demandeur.all
  end

  # GET /demandeurs/1
  # GET /demandeurs/1.json
  def show
  end

  # GET /demandeurs/new
  def new
    @demandeur = Demandeur.new
  end

  # GET /demandeurs/1/edit
  def edit
  end

  # POST /demandeurs
  # POST /demandeurs.json
  def create
    @demandeur = Demandeur.new(demandeur_params)


      if @demandeur.save
        redirect_to @demandeur
      else
        render :new 
      end
    
  end

  # PATCH/PUT /demandeurs/1
  # PATCH/PUT /demandeurs/1.json
  def update

      if @demandeur.update(demandeur_params)
        redirect_to @demandeur
      else
        render :edit
      end
  end

  # DELETE /demandeurs/1
  # DELETE /demandeurs/1.json
  def destroy
    @demandeur.destroy
    redirect_to(demandeurs_path)
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_demandeur
      @demandeur = Demandeur.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def demandeur_params
      params.require(:demandeur).permit(:name, :surname, :age, :city, :phone, :email, :skill, :qualification, :licence)
    end
end

poleEmploi/app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  before_action :set_employer, only: [:show, :edit, :update, :destroy]

  # GET /employers
  # GET /employers.json
  def index
    @employers = Employer.all
  end

  # GET /employers/1
  # GET /employers/1.json
  def show
  end

  # GET /employers/new
  def new
    @employer = Employer.new
  end

  # GET /employers/1/edit
  def edit
  end

  # POST /employers
  # POST /employers.json
  def create
    @employer = Employer.new(employer_params)

    if @employer.save
      redirect_to @employer
    else
      render :new
    end
  end

  # PATCH/PUT /employers/1
  # PATCH/PUT /employers/1.json
  def update
    if @employer.update(employer_params)
      redirect_to @employer
    else
      render :edit
    end
  end

  # DELETE /employers/1
  # DELETE /employers/1.json
  def destroy
    @employer.destroy
    redirect_to(employers_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employer
      @employer = Employer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employer_params
      params.require(:employer).permit(:companyName)
    end
end

poleEmploi/app/controllers/home_controller.rb
class HomeController < ApplicationController


	def index
	end


end

poleEmploi/app/controllers/reponses_controller.rb
class ReponsesController < ApplicationController
  before_action :set_reponse, only: [:show, :edit, :update, :destroy]

  # GET /reponses
  # GET /reponses.json
  def index
    @annonce = Annonce.all
  end

  # GET /reponses/1
  # GET /reponses/1.json
  def show
  end

  # GET /reponses/new
  def new
    @reponse = Reponse.new
  end

  # GET /reponses/1/edit
  def edit
  end

  # POST /reponses
  # POST /reponses.json
  def create
    @reponse = Reponse.new(reponse_params)

      if @reponse.save
        redirect_to @reponse
      else
        render :new 
      end
  end

  # PATCH/PUT /reponses/1
  # PATCH/PUT /reponses/1.json
  def update
      if @reponse.update(reponse_params)
        redirect_to @reponse
      else
        render :edit
      end
  end

  # DELETE /reponses/1
  # DELETE /reponses/1.json
  def destroy
    @reponse.destroy
    redirect_to(reponses_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reponse
      @reponse = Reponse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reponse_params
      params.require(:reponse).permit(:id_society, :id_demandeur, :message)
    end
end

poleEmploi/app/helpers/annonces_helper.rb
module AnnoncesHelper
end

poleEmploi/app/helpers/application_helper.rb
module ApplicationHelper
end

poleEmploi/app/helpers/demandeurs_helper.rb
module DemandeursHelper
end

poleEmploi/app/helpers/employers_helper.rb
module EmployersHelper
end

poleEmploi/app/helpers/login_helper.rb
module LoginHelper
end

poleEmploi/app/helpers/reponses_helper.rb
module ReponsesHelper
end

poleEmploi/app/views/annonces/_form.html.erb
<%= form_with(model: annonce, local: true) do |form| %>
  <% if annonce.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(annonce.errors.count, "error") %> prohibited this annonce from being saved:</h2>

      <ul>
      <% annonce.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :annonce_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :annonce_description %>
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.number_field :salary, id: :annonce_salary %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :annonce_city %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone, id: :annonce_phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :annonce_email %>
  </div>

  <div class="field">
    <%= form.label :skill %>
    <%= form.text_field :skill, id: :annonce_skill %>
  </div>

  <div class="field">
    <%= form.label :qualification %>
    <%= form.text_field :qualification, id: :annonce_qualification %>
  </div>

  <div class="field">
    <%= form.label :licence %>
    <%= form.text_field :licence, id: :annonce_licence %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

poleEmploi/app/views/annonces/edit.html.erb
<h1>Editing Annonce</h1>

<%= render 'form', annonce: @annonce %>

<%= link_to 'Show', @annonce %> |
<%= link_to 'Back', annonces_path %>

poleEmploi/app/views/annonces/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS: You can use this stylesheet to override any Bootstrap styles and/or apply your own styles -->
    <link href="css/custom.css" rel="stylesheet">

    <!-- Custom Fonts from Google -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    
</head>

<body>

    <!-- Navigation -->
    <nav id="siteNav" class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            
            <!-- Logo-->
            <div class="navbar-header">
                <a class="navbar-brand" href="#"> <%= image_tag "logo.png" %> </a>
            </div>

            <!-- Navbar HEADER -->
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active">
                        home
                    </li>
                    <li>
                        
                    </li>
                    <li>
                        <%= link_to 'Offres', annonces_url %>
                    </li>
                    <li>
                        <a href="#">Back Office</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

  <div class="headerBlank"></div>

     <section class="content content-2">
        
                  <p id="notice"><%= notice %></p>

                  <h1>Offres</h1>

                  <table>
                    <thead>
                      <tr>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Salary</th>
                        <th>City</th>
                        <th>Phone</th>
                        <th>Email</th>
                        <th>Skill</th>
                        <th>Qualification</th>
                        <th>Licence</th>
                        <th colspan="3"></th>
                      </tr>
                    </thead>

                    <tbody>
                      <% @annonces.each do |annonce| %>
                        <tr>
                          <td><%= annonce.title %></td>
                          <td><%= annonce.description %></td>
                          <td><%= annonce.salary %></td>
                          <td><%= annonce.city %></td>
                          <td><%= annonce.phone %></td>
                          <td><%= annonce.email %></td>
                          <td><%= annonce.skill %></td>
                          <td><%= annonce.qualification %></td>
                          <td><%= annonce.licence %></td>
                          <td><%= link_to 'Show', annonce %></td>
                          <td><%= link_to 'Edit', edit_annonce_path(annonce) %></td>
                          <td><%= link_to 'Destroy', annonce, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>

                  <br>

                  <%= link_to 'New annonce', new_annonce_path %>

    </section>    

 

    <!-- jQuery -->
    <script src="js/jquery-1.11.3.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="js/jquery.easing.min.js"></script>
    
    <!-- Custom Javascript -->
    <script src="js/custom.js"></script>

</body>

</html>

poleEmploi/app/views/annonces/new.html.erb
<h1>New Annonce</h1>

<%= render 'form', annonce: @annonce %>

<%= link_to 'Back', annonces_path %>

poleEmploi/app/views/annonces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @annonce.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @annonce.description %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @annonce.salary %>
</p>

<p>
  <strong>City:</strong>
  <%= @annonce.city %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @annonce.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @annonce.email %>
</p>

<p>
  <strong>Skill:</strong>
  <%= @annonce.skill %>
</p>

<p>
  <strong>Qualification:</strong>
  <%= @annonce.qualification %>
</p>

<p>
  <strong>Licence:</strong>
  <%= @annonce.licence %>
</p>

<%= link_to 'Edit', edit_annonce_path(@annonce) %> |
<%= link_to 'Back', annonces_path %>

poleEmploi/app/views/demandeurs/_form.html.erb
<%= form_with(model: demandeur, local: true) do |form| %>
  <% if demandeur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(demandeur.errors.count, "error") %> prohibited this demandeur from being saved:</h2>

      <ul>
      <% demandeur.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :demandeur_name %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname, id: :demandeur_surname %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: :demandeur_age %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :demandeur_city %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone, id: :demandeur_phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :demandeur_email %>
  </div>

  <div class="field">
    <%= form.label :skill %>
    <%= form.text_field :skill, id: :demandeur_skill %>
  </div>

  <div class="field">
    <%= form.label :qualification %>
    <%= form.text_field :qualification, id: :demandeur_qualification %>
  </div>

  <div class="field">
    <%= form.label :licence %>
    <%= form.text_field :licence, id: :demandeur_licence %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

poleEmploi/app/views/demandeurs/edit.html.erb
<h1>Editing Demandeur</h1>

<%= render 'form', demandeur: @demandeur %>

<%= link_to 'Show', @demandeur %> |
<%= link_to 'Back', demandeurs_path %>

poleEmploi/app/views/demandeurs/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS: You can use this stylesheet to override any Bootstrap styles and/or apply your own styles -->
    <link href="css/custom.css" rel="stylesheet">

    <!-- Custom Fonts from Google -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    
</head>

<body>

    <!-- Navigation -->
    <nav id="siteNav" class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            
            <!-- Logo-->
            <div class="navbar-header">
                <a class="navbar-brand" href="#"> <%= image_tag "logo.png" %> </a>
            </div>

            <!-- Navbar HEADER -->
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active">
                        home
                    </li>
                    <li>
                        
                    </li>
                    <li>
                        <%= link_to 'Demandeurs', demandeurs_url %>
                    </li>
                    <li>
                        <a href="#">Back Office</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

  <div class="headerBlank"></div>

     <section class="content content-2">
        
                  <p id="notice"><%= notice %></p>

                  <h1>Demandeurs</h1>

                  <table>
                    <thead>
                      <tr>
                        <th>Name</th>
                        <th>Surname</th>
                        <th>Age</th>
                        <th>City</th>
                        <th>Phone</th>
                        <th>Email</th>
                        <th>Skill</th>
                        <th>Qualification</th>
                        <th>Licence</th>
                        <th colspan="3"></th>
                      </tr>
                    </thead>

                    <tbody>
                      <% @demandeurs.each do |demandeur| %>
                        <tr>
                          <td><%= demandeur.name %></td>
                          <td><%= demandeur.surname %></td>
                          <td><%= demandeur.age %></td>
                          <td><%= demandeur.city %></td>
                          <td><%= demandeur.phone %></td>
                          <td><%= demandeur.email %></td>
                          <td><%= demandeur.skill %></td>
                          <td><%= demandeur.qualification %></td>
                          <td><%= demandeur.licence %></td>
                          <td><%= link_to 'Show', demandeur %></td>
                          <td><%= link_to 'Edit', edit_demandeur_path(demandeur) %></td>
                          <td><%= link_to 'Destroy', demandeur, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>

                  <br>

                  <%= link_to 'New Demandeur', new_demandeur_path %>

    </section>    

 

    <!-- jQuery -->
    <script src="js/jquery-1.11.3.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="js/jquery.easing.min.js"></script>
    
    <!-- Custom Javascript -->
    <script src="js/custom.js"></script>

</body>

</html>

poleEmploi/app/views/demandeurs/new.html.erb
<h1>New Demandeur</h1>

<%= render 'form', demandeur: @demandeur %>

<%= link_to 'Back', demandeurs_path %>

poleEmploi/app/views/demandeurs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @demandeur.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @demandeur.surname %>
</p>

<p>
  <strong>Age:</strong>
  <%= @demandeur.age %>
</p>

<p>
  <strong>City:</strong>
  <%= @demandeur.city %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @demandeur.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @demandeur.email %>
</p>

<p>
  <strong>Skill:</strong>
  <%= @demandeur.skill %>
</p>

<p>
  <strong>Qualification:</strong>
  <%= @demandeur.qualification %>
</p>

<p>
  <strong>Licence:</strong>
  <%= @demandeur.licence %>
</p>

<%= link_to 'Edit', edit_demandeur_path(@demandeur) %> |
<%= link_to 'Back', demandeurs_path %>

poleEmploi/app/views/employers/_form.html.erb
<%= form_with(model: employer, local: true) do |form| %>
  <% if employer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employer.errors.count, "error") %> prohibited this employer from being saved:</h2>

      <ul>
      <% employer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :companyName %>
    <%= form.text_field :companyName, id: :employer_companyName %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

poleEmploi/app/views/employers/edit.html.erb
<h1>Editing Employer</h1>

<%= render 'form', employer: @employer %>

<%= link_to 'Show', @employer %> |
<%= link_to 'Back', employers_path %>

poleEmploi/app/views/employers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employers</h1>

<table>
  <thead>
    <tr>
      <th>Companyname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employers.each do |employer| %>
      <tr>
        <td><%= employer.companyName %></td>
        <td><%= link_to 'Show', employer %></td>
        <td><%= link_to 'Edit', edit_employer_path(employer) %></td>
        <td><%= link_to 'Destroy', employer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employer', new_employer_path %>

poleEmploi/app/views/employers/new.html.erb
<h1>New Employer</h1>

<%= render 'form', employer: @employer %>

<%= link_to 'Back', employers_path %>

poleEmploi/app/views/employers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Companyname:</strong>
  <%= @employer.companyName %>
</p>

<%= link_to 'Edit', edit_employer_path(@employer) %> |
<%= link_to 'Back', employers_path %>

poleEmploi/app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS: You can use this stylesheet to override any Bootstrap styles and/or apply your own styles -->
    <link href="css/custom.css" rel="stylesheet">

    <!-- Custom Fonts from Google -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    
</head>

<body>

    <!-- Navigation -->
    <nav id="siteNav" class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            
            <!-- Logo-->
            <div class="navbar-header">
                <a class="navbar-brand" href="#"> <%= image_tag "logo.png" %> </a>
            </div>

            <!-- Navbar HEADER -->
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active">
                        <a href="#">Home</a>
                    </li>
                    <li>
                        <%= link_to 'Offres', annonces_url %>
                    </li>
                    <li>
                         <%= link_to 'Demandeurs', demandeurs_url %>
                    </li>
                    <li>
                        <a href="#">Back Office</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

	<div class="headerBlank"></div>

     <section class="content content-2">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                	<h2 class="section-header">546 320 offres d'emploi disponibles !</h2>
                	<p class="lead text-light">Holisticly predominate extensible testing procedures for reliable supply chains. Dynamically innovate resource-leveling customer service for state of the art customer service.</p>
                </div>    
                <div class="col-sm-6">

                	<h2 class="section-header">S'indentifier</h2>

                    <%= form_tag "home/index", method: :post do %>
                      <input style="color:black" type="text" name="name" placeholder="email" />
                      <input style="color:black" type="password" name="password" placeholder="mot de passe" />
                      <input style="color:black" type="submit" value="Se connecter" />
                    <% end %>

                    <%= link_to 'S\'inscrire', new_demandeur_path %>
                
                </div>            
            </div>
        </div>
    </section>    

 

    <!-- jQuery -->
    <script src="js/jquery-1.11.3.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="js/jquery.easing.min.js"></script>
    
    <!-- Custom Javascript -->
    <script src="js/custom.js"></script>

</body>

</html>

poleEmploi/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PoleEmploi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <link rel="stylesheet" href="http://poleEmploi.com/assets/bootstrap.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">	 
      <%= yield %>
    </div> 
 </body>
</html>

poleEmploi/app/views/reponses/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS: You can use this stylesheet to override any Bootstrap styles and/or apply your own styles -->
    <link href="css/custom.css" rel="stylesheet">

    <!-- Custom Fonts from Google -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    
</head>

<body>

    <!-- Navigation -->
    <nav id="siteNav" class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            
            <!-- Logo-->
            <div class="navbar-header">
                <a class="navbar-brand" href="#"> <%= image_tag "logo.png" %> </a>
            </div>

            <!-- Navbar HEADER -->
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active">
                        home
                    </li>
                    <li>
                        
                    </li>
                    <li>
                        <%= link_to 'Offres', annonces_url %>
                    </li>
                    <li>
                        <a href="#">Back Office</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

  <div class="headerBlank"></div>

     <section class="content content-2">
        
                  <p id="notice"><%= notice %></p>

                  <h1>Choix de l'annonce</h1>

                  <table>
                    <thead>
                      <tr>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Salary</th>
                        <th>City</th>
                        <th>Phone</th>
                        <th>Email</th>
                        <th>Skill</th>
                        <th>Qualification</th>
                        <th>Licence</th>
                        <th colspan="3"></th>
                      </tr>
                    </thead>

                    <tbody>
                      <% @annonce.each do |annonce| %>
                        <tr>
                          <td><%= annonce.title %></td>
                          <td><%= annonce.description %></td>
                          <td><%= annonce.salary %></td>
                          <td><%= annonce.city %></td>
                          <td><%= annonce.phone %></td>
                          <td><%= annonce.email %></td>
                          <td><%= annonce.skill %></td>
                          <td><%= annonce.qualification %></td>
                          <td><%= annonce.licence %></td>
                          <td><%= link_to 'Show', annonce %></td>
                          <td><%= link_to 'Edit', edit_annonce_path(annonce) %></td>
                          <td><%= link_to 'Destroy', annonce, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>

                  <br>

                  <%= link_to 'New annonce', new_annonce_path %>

    </section>    

 

    <!-- jQuery -->
    <script src="js/jquery-1.11.3.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="js/jquery.easing.min.js"></script>
    
    <!-- Custom Javascript -->
    <script src="js/custom.js"></script>

</body>

</html>